<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>fr.molzonas.mcfr</groupId>
    <artifactId>ekeep</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <modules>
        <module>api</module>
        <module>core</module>
    </modules>

    <properties>
        <revision>0.1-SNAPSHOT</revision>

        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!--                Versions properties                -->
        <paper.api.version>1.20.6-R0.1-SNAPSHOT</paper.api.version>
        <adventure.version>4.17.0</adventure.version>
        <minimessage.version>4.17.0</minimessage.version>
        <cloud.version>1.8.4</cloud.version>
        <configurate.version>4.2.0</configurate.version>
        <caffeine.version>3.1.8</caffeine.version>
        <hikari.version>5.1.0</hikari.version>
        <jdbi.version>3.45.1</jdbi.version>
        <flyway.version>10.17.0</flyway.version>
        <fastutil.version>8.5.12</fastutil.version>
        <jackson.version>2.17.2</jackson.version>
        <bstats.version>3.0.2</bstats.version>
        <mockbukkit.version>3.93.2</mockbukkit.version>
        <luckperms.api.version>5.4</luckperms.api.version>
        <protocollib.version>5.4.0</protocollib.version>
        <modelengine.version>R4.0.8</modelengine.version>
        <mythicmobs.version>5.6.1</mythicmobs.version>
        <acf.version>0.5.1-SNAPSHOT</acf.version>
        <!--                                                    -->
    </properties>

    <repositories>
        <repository>
            <id>papermc-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>nexus</id>
            <url>https://mvn.lumine.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>aikar</id>
            <url>https://repo.aikar.co/content/groups/aikar/</url>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>fr.molzonas.mcfr</groupId>
                <artifactId>ekeep-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>io.papermc.paper</groupId>
                <artifactId>paper-api</artifactId>
                <version>${paper.api.version}</version>
                <scope>provided</scope>
            </dependency>

            <!-- Force Checker Framework version to 3.42.0 -->
            <dependency>
                <groupId>org.checkerframework</groupId>
                <artifactId>checker-qual</artifactId>
                <version>3.42.0</version>
            </dependency>

            <!-- Force Jackson version to 2.17.2 -->
            <dependency>
                <groupId>com.fasterxml.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>2.17.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Force jackson-dataformat-toml used by Flyway (2.17.2) -->
            <dependency>
                <groupId>com.fasterxml.jackson.dataformat</groupId>
                <artifactId>jackson-dataformat-toml</artifactId>
                <version>2.17.2</version>
            </dependency>

            <!-- Force jetbrains annotation used by this plugin and Adventure -->
            <dependency>
                <groupId>org.jetbrains</groupId>
                <artifactId>annotations</artifactId>
                <version>24.1.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <distributionManagement>
        <repository>
            <id>github</id>
            <url>https://maven.pkg.github.com/Molzonas/EkEep</url>
        </repository>
        <snapshotRepository>
            <id>github</id>
            <url>https://maven.pkg.github.com/Molzonas/EkEep</url>
        </snapshotRepository>
    </distributionManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.5.0</version>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>3.4.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireJavaVersion>
                                    <version>[21,)</version>
                                </requireJavaVersion>
                                <requireMavenVersion>
                                    <version>[3.8,)</version>
                                </requireMavenVersion>
                                <dependencyConvergence/>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- Shading -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.2</version>
            </plugin>
            <!-- Tests -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.3.0</version>
            </plugin>
        </plugins>
    </build>
</project>